theme: minima
title: Rtips آر تِبس.
author: yOOstech
description: مرحبا بكم هنا في آر تِبس.  ستجد ون هنا روابط ، نصائح ، تعليمات مع شرح باللغة العربية لأرضية آر. هذا الموقع رديف لمستودع https://github.com/yOOs-dz/R_tips_ar
و الذي  يحمل عناصر أولية لمشروع أر تِبس. مرحبا بكل مساهمة على الموقع أعلاه.
